### ISSUE TITLE
[BUG] - *ENTER TITLE*

### ISSUE THREAD

**Issue by it-sugar** [NovatecConsulting/novatec-service-dependency-graph-panel#104]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'length')
    at eval (Utils.ts:13:40)
    at A (Utils.ts:3:25)
    at F (Statistics.tsx:63:14)
when requests count equals zero

**To Reproduce**
create some data and make requests count equals zero

**Screenshots**
![企业微信截图_20220315162314](https://user-images.githubusercontent.com/31034879/158335977-75fd4d47-21c6-4528-b222-2695f6848fe7.png)

**Comment by MariusBrill** [comment]
Hey @it-sugar,

Thank you for reporting this issue! We will fix it in our upcoming major release.

Best regards
Marius
