### ISSUE TITLE
[BUG] - *Error loading: novatec-sdg-panel *

### ISSUE THREAD

**Issue by pratisha-blk** [NovatecConsulting/novatec-service-dependency-graph-panel#128]
**Describe the bug**
For Grafana Version **Grafana v10.0.1-cloud.2.a7a20fbf (e6fd971a0e)** service-dependency-graph-panel is not loading andshowing this error
**Error loading: novatec-sdg-panel**

**To Reproduce**
Create a Service Dependency Graph panel on Grafana v10.0.1-cloud.2.a7a20fbf (e6fd971a0e) version

**Expected behavior**
It should load and show the panel

**Screenshots**
![SDG](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/assets/136429104/2e5df5ab-a13f-4797-9f2e-9fb0f6e40cfd)

**Your Setup:**
**Grafana v10.0.1-cloud.2.a7a20fbf (e6fd971a0e)**

**Comment by zenmetsu** [comment]
The issue appears to be common to grafana 10.  I am running Grafana OSS and experience the same issue.

```
grafana-server -v
Version 10.0.0 (commit: 81d85ce802, branch: HEAD)
```

**Comment by pratisha-blk** [comment]
Dev console logs while trying to load the panel : 

Error loading panel plugin: novatec-sdg-panel TypeError: Cannot assign to read only property 'add' of object '[object Object]'
    at Function.assign (<anonymous>)
    at eval (cytoscape.cjs.js:13332:3)
    at Array.forEach (<anonymous>)
    at Object.eval (cytoscape.cjs.js:13331:162)
    at Object.eval (module.js:2:377179)
    at n (bootstrap:19:22)
    at Module.eval (module.js:2:628027)
    at n (bootstrap:19:22)
    at eval (bootstrap:83:10)
    at eval (module.js:2:1037)

**Comment by pratisha-blk** [comment]
Any updates or workarounds for this?

**Comment by kbitra** [comment]
Just trying to see if any resolutions on this.. this is a blocker for me.. and I really like this panel..

**Comment by zhaolj214** [comment]
grafana-10.0.1 has a error log：
WARN Skipping plugin loading as it's a duplicate logger=plugin.loader pluginID=novatec-sdg-panel
ERROR Dashboard not found logger=context userId=1 orgId=1 uname=admin error="Dashboard not found" remote_addr=[::1] traceID=

**Comment by kbitra** [comment]
helloooo.. anyone has any idea ?

**Comment by germankuber** [comment]
Anyone has any idea ?

**Comment by levinkerschberger** [comment]
Since Version 1**0.1.0**, the SDG-Panel is available again.

Seems like there is some kind of Bug in Cytoscape, the Graph Rendering Library, or Grafana 10.0.x, which prevents the plugin to load properly .

I´d suggest to upgrade Grafana to **Version >= 10.1.x** and troubles will be gone.
